config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  resources :squads, only: [:index, :show, :new, :create, :update, :destroy]

  resources :courts, only: [:index, :show, :update] do
    resources :games, only: [:show, :new, :edit, :create, :update, :destroy]
  end

  resources :players, only: [:show, :new, :create, :edit, :update] 
  get '/current_user' => 'players#current'
  #get '/popular_squads' => 'squads#popular'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  
  post '/sessions', to: 'sessions#create'

  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/court.rb
class Court < ApplicationRecord
    has_many :games
    has_many :favorites, dependent: :destroy
    has_many :players, through: :favorites 
    validates :location, presence: true
    validates :name, presence: true

    def upcoming_games
        self.games.where("time > ?", Time.zone.now).order(time: "ASC")
    end

    def favorite_count
        self.favorites.count
    end

    def is_favorite?(player)
        !!self.favorites.find_by(player: player)
    end

    def add_favorite(player)
        self.favorites.find_or_create_by(player:player)
    end

    def remove_favorite(favorite)
        favorite.destroy
    end

    def add_or_remove_favorite(player)
        favorite = self.favorites.find_by(player:player)
        if favorite
            remove_favorite(favorite)
        else
            self.add_favorite(player)
        end
    end

end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
    before_action :require_login, only:[:update, :show]
    def index
        @courts = Court.all
        respond_to do |format|
            format.html { render :index }
            format.json { render json: @courts, each_serializer: SimpleCourtSerializer }
        end
    end

    def show
        @court = Court.find(params[:id])
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @court, serializer: CompleteCourtSerializer, include: [:upcoming_games] }
        end
    end

    def update
        @court = Court.find(params[:id])
        @court.add_or_remove_favorite(current_player)
        respond_to do |format|
            format.html {redirect_to court_path(@court)}
            format.json {render json: @court, serializer: CompleteCourtSerializer, include: [:upcoming_games]}
        end
    end
end

app/helpers/courts_helper.rb
module CourtsHelper

end

app/views/courts/index.html.erb
<h1>Courts</h1>
<button class="js-sort-courts">Sort Courts!</button>
<div class="courts-list">
    <% @courts.each do |court| %>
        <a class="content-box" href=<%= court_path(court)%>>
            <h3><%=court.name%></h3>
            <%= court.location %> <br>
            <%= court.upcoming_games.count.to_s + " upcoming games"%>
        </a>
    <% end %>
</div>

app/views/courts/show.html.erb
<h1><%= @court.name %></h1>
<div class="court-info">
    <h3>Address: <%= @court.location %></h3>
    <div class="favorite">
        <%= button_to (@court.is_favorite?(current_player) ? "REMOVE FROM FAVORITES" : "ADD TO FAVORITES"), court_path(@court), :method => :patch  %>
        <h3>Favorited By <%= @court.favorite_count %> Players</h3>
    </div>

    <div class = "content-box">
        <h2>Upcoming Games</h2>
        <div class="games_list">
            <% @court.upcoming_games.each do |game|%>
                <%= link_to "#{display_date_and_time(game.time)} (#{game.player_count})", court_game_path(@court, game) %> <br>
            <% end %>
        </div>
    </div>
    <% if current_player %>
        <h2>Create New Game</h2>
        <%= form_tag court_games_path(@court), class: "new-game" do%>
            <%= hidden_field_tag "game[court_id]", @court.id %>
            Skill Level <br>
            <%= select_tag "game[skill_level]", options_for_select(Game.skill_level_array, Game.skill_level_array.first) %> <br>
            Time <br> 
            <%= datetime_field_tag "game[time]", current_time_for_form_tag %> <br>

            <%= submit_tag "Create Game" %>
        <% end%>
    <% end %>
</div>