config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  resources :squads, only: [:index, :show, :new, :create, :update, :destroy]

  resources :courts, only: [:index, :show, :update] do
    resources :games, only: [:show, :new, :edit, :create, :update, :destroy]
  end

  resources :players, only: [:show, :new, :create, :edit, :update] 
  get '/current_user' => 'players#current'
  #get '/popular_squads' => 'squads#popular'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  
  post '/sessions', to: 'sessions#create'

  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
    has_secure_password
    has_many :squad_players, dependent: :destroy
    has_many :squads, through: :squad_players
    has_many :admin_squads, -> {merge(SquadPlayer.admin)}, :source => :squad, through: :squad_players
    has_many :game_players, dependent: :destroy
    has_many :games, through: :game_players
    
    has_many :upcoming_games, -> {where("time > ?", Time.zone.now).order(time: "ASC")}, :source => :game, through: :game_players
    has_many :admin_games, -> {merge(GamePlayer.admin).where("time > ?", Time.zone.now).order(time: "ASC")}, :source => :game, through: :game_players
    has_many :favorites, dependent: :destroy
    has_many :courts, through: :games
    has_many :favorite_courts, through: :favorites, source: :court

    validates :name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password, presence: true, on: [:create]
 

    # def upcoming_games
    #     self.games.where("time > ?", Time.zone.now).order(time: "ASC")
    # end

    def self.find_or_create_by_omniauth_hash(auth_hash)
        self.where(email: auth_hash[:info][:email]).first_or_create do |player|
            player.name = auth_hash[:info][:name] if !player.name
            player.password = SecureRandom.hex
        end
    end

    def admin_squads_count
        self.admin_squads.count
    end

    def join_game(game)
        game.add_player(self)
    end

    # def create_game_from_hash(game_hash)
    #     self.games.new(game_hash).tap do |game|
    #         game.make_admin(self) if game.save
    #     end
    # end

    # def create_squad_from_hash(squad_hash)
    #     self.squads.build(squad_hash) #do |squad|
    #         #squad.make_admin(self) if squad.save
    #     #end
    # end

    def add_favorite(court)
        self.favorites.find_or_create_by(court:court)
    end

    def remove_favorite(court)
        self.favorites.find_or_create_by(court:court).destroy
    end

    def is_admin_of?(game_or_squad)
        !!game_or_squad.admins.find_by(id: self.id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :require_login, only:[:current]
    def current
        @player = current_player ? current_player : Player.new
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @player}
        end
    end

    def show
        @player = Player.find(params[:id])
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @player, include: [:squads, :upcoming_games] }
        end
    end

    def new
        @player = Player.new
    end

    def create
        @player = Player.new(player_params) 
        if !@player.valid? || params[:player][:password] != params[:player][:password_confirmation]
            set_flash_errors(@player)
            render :new
        else
            @player.save
            session[:player_id] = @player.id
            redirect_to root_path
        end
    end

    private
    def player_params
        params.require(:player).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/new.html.erb
<div class="sign-up">
  <%= link_to('Sign up with Facebook', '/auth/facebook') %> <br>
  <div> or</div>
  <p> <strong> Sign Up with your Email Address </strong></p>
        
  <%= form_for @player, url: '/players' do |f| %>
    <%= f.text_field :email, placeholder: "Email" %> 
    <%= f.text_field :name, placeholder: "Your Player Name" %> 
    <%= f.password_field :password, placeholder: "Password" %> 
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %> 
    <%= f.submit "Sign Up" %> 
  <% end %>
       
  
</div>

app/views/players/show.html.erb
<h1 user-id=<%= @player.id %>><%= @player == current_player ? "My Profile" :  "#{@player.name}'s Profile"%></h1>
<div class="profile">
    <div class="content-box js-player-games">
        <h2> Upcoming Games</h2>
        <!--
        <% @player.upcoming_games.each do |game|%>
            <div>
                <strong><%= link_to game.court_name, court_path(game.court) %></strong> <br>
                <%= player_admin_button(path: court_game_path(game.court, game), text: "LEAVE", params_hash: {player_id: current_player.id}) if @player == current_player %> 
                <%= link_to display_date_and_time(game.time), court_game_path(game.court, game) %> 
                <strong><%= " Admin" if @player.is_admin_of?(game) %></strong> 
            </div>
        <% end %>
        
        -->
    </div> 

    <div class="content-box js-player-squads">
        <h2>Squads</h2>
        
        <% @player.squads.each do |squad|%>
            <div>
                <%= link_to "#{squad.name} (#{squad.player_count} players)", squad_path(squad) %>
                <strong><%= " Admin" if @player.is_admin_of?(squad) %></strong>
            </div>
        <% end %>
        
    </div>

    <div class="content-box">
        <h2>Favorite Courts</h2>
        <% @player.favorite_courts.each do |court|%>
            <div>
                <%= link_to "#{court.name} (#{court.upcoming_games.count} games)", court_path(court) %>
            </div>
        <% end%>
    </div>
</div>

<script>
    //$(function () {
     //  alert("I did it")
//  $(".js-next").on("click", function(event) {
 //   event.preventDefault()
 //   var nextId = parseInt($(".js-next").attr("data-id")) + 1;
 //   $.get("/posts/" + nextId + ".json", function(data) {
 //     // get post
 //     var post = data;
 //     $(".postTitle").text(post["title"]);
 //     $(".postBody").text(post["description"]);
 //     // re-set the id to current on the link
 //     $(".js-next").attr("data-id", post["id"]);
 //   });
 // });
//});
</script>