config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  resources :squads, only: [:index, :show, :new, :create, :update, :destroy]

  resources :courts, only: [:index, :show, :update] do
    resources :games, only: [:show, :new, :edit, :create, :update, :destroy]
  end

  resources :players, only: [:show, :new, :create, :edit, :update] 
  get '/current_user' => 'players#current'
  #get '/popular_squads' => 'squads#popular'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  
  post '/sessions', to: 'sessions#create'

  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickUpGames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <header>
      <div>Pick Up Logo</div>
      <nav>
        <ul>
          <li><%= link_to "Home", root_url %></li>
          <!--<li><%= link_to 'Courts', courts_path %></li>-->
          <li><a href="#" id="js-courts"> Courts </a></li>
          <li><%= link_to 'Squads', squads_path %></li>
          <% if current_player %>
            <li><%= link_to 'My Profile', player_path(current_player) %></li>
            <li><%= link_to 'Log Out', logout_path, :method => :post %></li>
          <% else%>
            <li><%= link_to "Sign Up", new_player_url %></li>
            <li><%= link_to "Log In", login_url %></li>
          <% end %>
        </ul>
      </nav>
    </header>

 

    <!-- content -->
    <main>
        <% flash.each do |key, messages| %>
          <% messages.each do |message|%>
            <div class="alert alert-<%= key %>"><%= message %></div>
          <% end %>
        <% end %>
      <%= yield %>
    </main>
  </body>
</html>